# -*- coding: utf-8 -*-
"""Task10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BfHG3R-L6wazpUm64dJDNah0q4-DbyY
"""

# base class
class BankAccount:
    def __init__(self, name, balance):
        self.name = name
        self.__balance = balance  # private variable

    def deposit(self, amount):
        self.__balance += amount
        print("deposited:", amount)

    def withdraw(self, amount):
        if amount <= self.__balance:
            self.__balance -= amount
            print("withdrawn:", amount)
        else:
            print("insufficient balance")

    def get_balance(self):
        return self.__balance


# child class
class SavingsAccount(BankAccount):
    def __init__(self, name, balance, interest):
        super().__init__(name, balance)
        self.interest = interest

    def add_interest(self):
        bal = self.get_balance()
        interest_amount = bal * self.interest / 100
        self.deposit(interest_amount)


# create objects
acc1 = BankAccount("tushar", 5000)
acc2 = SavingsAccount("rahul", 8000, 5)

acc1.deposit(1000)
acc1.withdraw(2000)
print("balance:", acc1.get_balance())

acc2.deposit(2000)
acc2.add_interest()
print("balance:", acc2.get_balance())